---
dependencies:
  - ivansible.base.linux     # for common linux defaults, handlers, modules
  - ivansible.base.asterisk  # for common asterisk defaults and handlers
  - ivansible.base.backup    # for postgresql_db_restore_encrypted.yml
  - ivansible.base.cert      # for default certbot settings
  ## the following roles are imported directly from tasks:
  # - ivansible.linux.docker

galaxy_info:
  role_name: ast_core
  author: "Ivan Andreev"
  description: "deploy asterisk server on linux"
  company: "IvanSible"
  license: MIT
  min_ansible_version: 2.9

  platforms:
    - name: Ubuntu
      versions:
        - xenial
        - bionic

  galaxy_tags:
    - linux
    - asterisk

  github_branch: master
...
