---
dependencies:
  - ivansible.base.asterisk  # for common asterisk defaults and handlers
  # this and other roles really depend on asterisk.core, but the inclusion
  # should be done explicitly in playbook to avoid repetitive execution.
  # - ivansible.asterisk.core

galaxy_info:
  role_name: ast_billing
  author: "Ivan Andreev"
  description: "tariff parser and trunk selector for asterisk"
  company: "IvanSible"
  license: MIT
  min_ansible_version: 2.5

  platforms:
    - name: Ubuntu
      versions:
        - xenial
        - bionic

  galaxy_tags:
    - linux
    - asterisk
    - billing

  github_branch: master
...
