---
# handlers for ivansible.ast_core

# inherited from lin_base:
# - reload systemd daemon
# - reload ubuntu firewall

# inherited from ast_base:
# - restart asterisk service
# - reload asterisk service
...
