---
# handlers file for ivansible.asterisk_core

# inherited from lin_base:
# - reload systemd daemon
# - reload ubuntu firewall

# inherited from asterisk_base:
# - restart asterisk service
# - reload asterisk service
...
