---
dependencies: []

galaxy_info:
  role_name: asterisk_providers
  author: "Ivan Andreev"
  description: "configure asterisk for calls via voip providers"
  company: "IvanSible"
  license: MIT
  min_ansible_version: 2.5

  platforms:
    - name: Ubuntu
      versions:
        - xenial
        - bionic

  galaxy_tags:
    - linux
    - ansible

  github_branch: master
...
