---
dependencies:
  - ivansible.asterisk_base  # for common asterisk defaults and handlers
  # this and other roles really depend on asterisk_core, but inclusion
  # should be done explicitly in playbook to avoid repetitive execution.
  #- ivansible.asterisk_core

galaxy_info:
  role_name: asterisk_providers
  author: "Ivan Andreev"
  description: "configure asterisk for calls via voip providers"
  company: "IvanSible"
  license: MIT
  min_ansible_version: 2.5

  platforms:
    - name: Ubuntu
      versions:
        - xenial
        - bionic

  galaxy_tags:
    - linux
    - asterisk

  github_branch: master
...
