---
# perform setup as a non-root user
- setup:
  become: no

# use import to become root globally
- name: become root
  import_tasks: root.yml
  become: yes
  tags: ast_soho_all

- meta: flush_handlers
...
