---
namespace: ivansible
name: asterisk
version: 1.0.0

description: Ansible collection for Asterisk

authors:
  - Ivan Andreev <ivandeex@gmail.com>

tags:
  - linux
  - asterisk
  - gigaset
  - soho
  - billing

# https://python-semanticversion.readthedocs.io/en/latest/#requirement-specification
# namespace.name: version_range
dependencies: {}

repository: https://github.com/ivansible/asterisk
documentation: https://github.com/ivansible/asterisk
homepage: https://github.com/ivansible/asterisk
issues: https://github.com/ivansible/asterisk/issues

readme: README.md
license: MIT

build_ignore:
  - '*.pyc'
  - '*.tar'
...
