---
dependencies:
  - ivansible.ast_base  # for common asterisk defaults and handlers
  # this and other roles actually depend on asterisk_core, but inclusion
  # should be done explicitly in playbook to avoid repetitive execution.
  # - ivansible.ast_core

galaxy_info:
  role_name: ast_soho
  author: "Ivan Andreev"
  description: "Connect home office Asterisk with SIP phones and SIP gateway provider"
  company: "IvanSible"
  license: MIT
  min_ansible_version: 2.5

  platforms:
    - name: Ubuntu
      versions:
        - xenial
        - bionic

  galaxy_tags:
    - linux
    - asterisk
    - soho

  github_branch: master
...
