---
- name: open asterisk SIP port for all/some networks in ferm
  # this step is separate because we want to specify
  # a list of ip networks given access to the non-tls port
  ferm_port:
    port: "{{ ast_sip_port }}"
    zone: "{{ ast_sip_allow_all |bool |ternary('external', 'media') }}"
    solo_zone: true
    comment: asterisk sip

- name: open asterisk RTP ports for all/some networks in ferm
  ferm_port:
    port: "{{ ast_rtp_port_start }}:{{ ast_rtp_port_end }}"
    proto: udp
    zone: "{{ ast_rtp_allow_all |bool |ternary('external', 'media') }}"
    solo_zone: true
    comment: asterisk rtp

- name: add networks allowed for asterisk sip port in ferm
  ferm_host:
    host: "{{ ast_allow_networks }}"
    zone: media
    comment: asterisk


- name: set connection limit on asterisk sip port
  ferm_rule:
    name: asterisk-sip-limit
    rule: |
      # Asterisk SIP Limit
      domain $ip_all table filter chain $INPUT {
        proto tcp syn dport {{ ast_sip_port }} {{ match_limit }} DROP;
        proto tcp syn dport {{ ast_tls_port }} {{ match_limit }} DROP;
        proto udp     dport {{ ast_sip_port }} {{ match_limit }} DROP;
      }
    hook: custom
    prio: 21
  vars:
    match_limit: >-
      mod hashlimit
      hashlimit-above {{ ast_sip_limit }}
      hashlimit-burst {{ ast_sip_burst }}
      hashlimit-mode srcip
      hashlimit-name asterisk-sip
  when: ast_sip_limit |d('')


- name: open asterisk sip-tls port in ferm
  ferm_port:
    port: "{{ ast_tls_port }}"
    zone: external
    comment: asterisk tls


- name: close asterisk ami ports in ferm
  ferm_port:
    port: "{{ ast_ami_port }},{{ ast_http_port }},{{ ast_https_port }}"
    zone: internal
    comment: asterisk ami

- name: disable annoying sip hackers in ferm
  ferm_host:
    host: "{{ ast_reject_networks }}"
    zone: blocked
    comment: asterisk
...
