---
- name: open asterisk sip port for all in ferm
  # this step is separate because we want to specify
  # a list of ip networks given access to the non-tls port
  ferm_port:
    port: 5060
    domain: external
    comment: asterisk sip
  when: ast_sip_allowed_networks |length == 0
        or 'any' in ast_sip_allowed_networks

- name: open asterisk sip port for some networks in ferm
  ferm_port:
    port: 5060
    domain: internal
    comment: asterisk sip
  when: ast_sip_allowed_networks |length > 0
        and 'any' not in ast_sip_allowed_networks

- name: add networks allowed for asterisk sip port in ferm
  ferm_host:
    host: "{{ ast_sip_allowed_networks }}"
    domain: internal
    comment: asterisk
  when: "'any' not in ast_sip_allowed_networks"


- name: open asterisk sip-tls port in ferm
  ferm_port:
    port: 5061
    domain: external
    comment: asterisk tls

- name: open asterisk rtp ports in ferm
  ferm_port:
    port: "{{ ast_rtp_port_start }}:{{ ast_rtp_port_end }}"
    proto: udp
    domain: external
    comment: asterisk rtp


- name: close asterisk ami ports in ferm
  ferm_port:
    port: "{{ ast_ami_port }},{{ ast_http_port }},{{ ast_https_port }}"
    domain: blocked
    comment: asterisk ami


- name: disable annoying sip hackers in ferm
  ferm_host:
    host: "{{ ast_reject_networks }}"
    domain: blocked
    comment: asterisk hackers
...
