---
- name: refresh host facts as a non-root user
  setup:
  become: no

- name: most asterisk tasks require privileged access
  import_tasks: root.yml
  become: true
  tags:
    - ast_core_all

- name: non-root asterisk tasks
  import_tasks: user.yml
  become: false
  tags:
    - ast_user
    - ast_core_all

- name: flush handlers
  meta: flush_handlers
...
