---
- name: configure syslog for asterisk
  copy:
    dest: /etc/rsyslog.d/33-asterisk.conf
    content: |
      :programname,isequal,"asterisk" /var/log/asterisk.log
      & stop
    force: false
  notify: restart syslog service


- name: rotate asterisk log files
  copy:
    dest: /etc/logrotate.d/asterisk
    content: |
      /var/log/asterisk/security
      /var/log/asterisk/debug
      /var/log/asterisk/messages
      /var/log/asterisk/full
      /var/log/asterisk/*_log
      {
          weekly
          maxsize 1M
          missingok
          rotate 4
          notifempty
          {{ commentout }}compress
          {{ commentout }}delaycompress
          sharedscripts
          postrotate
              invoke-rc.d asterisk logger-reload > /dev/null 2> /dev/null
          endscript
      }

      /var/log/asterisk.log {
          weekly
          maxsize 1M
          missingok
          rotate 4
          notifempty
          {{ commentout }}compress
          {{ commentout }}delaycompress
          sharedscripts
          postrotate
              invoke-rc.d rsyslog rotate > /dev/null 2> /dev/null
          endscript
      }
    force: true
  vars:
    commentout: "{{ '' if lin_compress_logs |bool or lin_compress_logs is none else '#' }}"
...
