---
# synchronize system time

- name: enable ntp sync
  command: timedatectl set-ntp true
  changed_when: false

- name: activate ntp daemon
  systemd:
    name: ntp
    state: started
    enabled: true
  changed_when: false

- name: step-sync local time
  # "-u" = use unprivileged port for outgoing packets,
  # helps when ntp service is running (or against firewalls),
  # so we don't have to stop/start ntp service
  command: ntpdate -u "{{ ast_ntp_server }}"
  changed_when: false
  when: ast_ntp_server != '' # noqa 602
...
