---
- name: grant remote user with access to asterisk
  user:
    name: "{{ ansible_user_id }}"
    groups: asterisk
    append: yes
  become: yes

- name: common bashrc customizations
  import_role:
    name: ivansible.dev_user
    tasks_from: bashrc.yml

- name: alias for running asterisk console
  lineinfile:
    # alias file must correspond with role ivansible.dev_user
    # https://github.com/ivansible/dev-user/blob/master/tasks/bashrc.yml
    path: ~/.local/bashrc/4alias.sh
    line: "alias astcli='setterm -linewrap off ; sudo asterisk -r ; setterm -linewrap on'"
    regexp: "^alias astcli *="
    insertafter: "^# END ANSIBLE"
  become: no
...
