---
- name: grant remote user with access to asterisk
  user:
    name: "{{ ansible_user_id }}"
    groups: asterisk
    append: true
  become: true

- name: check whether bash alias file already exists
  stat:
    path: ~/.local/bashrc/4alias.sh
  register: stat_bash_alias

- name: common bashrc customizations
  include_role:
    name: ivansible.dev_user
    tasks_from: bashrc.yml
    apply:
      tags:
        - ast_user
        - ast_core_all
      become: false
  when: not stat_bash_alias.stat.exists

- name: alias for running asterisk console
  lineinfile:
    # alias file must correspond with role ivansible.dev_user
    # https://github.com/ivansible/dev-user/blob/master/tasks/bashrc.yml
    path: ~/.local/bashrc/4alias.sh
    line: "alias astcli='setterm -linewrap off ; sudo asterisk -r ; setterm -linewrap on'"
    regexp: "^alias astcli *="
    insertafter: "^# END ANSIBLE"
  become: false
...
