---
- name: install tasks
  ansible.builtin.import_tasks: install.yml
  tags: ast_install

- name: ssl tasks
  ansible.builtin.import_tasks: ssl.yml
  tags: ast_ssl

- name: g729 tasks
  ansible.builtin.import_tasks: g729.yml
  tags: ast_g729

- name: config tasks
  ansible.builtin.import_tasks: config.yml
  tags: ast_config

- name: musiconhold tasks
  ansible.builtin.import_tasks: musiconhold.yml
  tags: ast_moh

## AGI script speaking current time in ru/en
- name: daytime tasks
  ansible.builtin.import_tasks: daytime.yml
  tags: ast_daytime

- name: database tasks
  ansible.builtin.import_tasks: database.yml
  tags: ast_database

- name: dialplan tasks
  ansible.builtin.import_tasks: dialplan.yml
  tags: ast_dialplan

- name: systemd tasks
  ansible.builtin.import_tasks: systemd.yml
  tags:
    - ast_systemd
    - ast_cpu_quota


- name: ufw tasks
  ansible.builtin.include_tasks: firewall-ufw.yml
  args:
    apply:
      become: true
      tags: ast_firewall
  when: lin_firewall == 'ufw'
  tags: ast_firewall

- name: ferm tasks
  ansible.builtin.include_tasks: firewall-ferm.yml
  args:
    apply:
      become: true
      tags:
        - skip_ansible_lint
        - ast_firewall
  when: lin_firewall == 'ferm'
  tags: ast_firewall

- name: anti-hackers tasks
  ansible.builtin.import_tasks: hackers.yml
  tags: ast_hackers


- name: syslog tasks
  ansible.builtin.import_tasks: syslog.yml
  when: lin_use_rsyslog |bool
  tags: ast_syslog

## asterisk rtp stream bridging requires precise local time
- name: time synch tasks
  ansible.builtin.import_tasks: timesync.yml
  when: ast_time_sync_enable |bool
  tags: ast_timesync
...
