---
- name: setup webui dns record in cloudflare
  community.general.cloudflare_dns:
    account_email: "{{ ast_webui_cloudflare_email }}"
    account_api_token: "{{ ast_webui_cloudflare_token }}"
    zone: "{{ ast_webui_server.split('.')[-2:] |join('.') }}"
    record: "{{ ast_webui_server.split('.')[:-2] |join('.') }}"
    type: "{{ 'AAAA' if ':' in ast_webui_bindip else 'A' }}"
    value: "{{ ast_webui_bindip }}"
    proxied: false
  become: false
  delegate_to: localhost
  when:
    - ast_webui_server |d('')
    - ast_webui_bindip |d('')
    - ast_webui_cloudflare_token |d('')
  tags: ast_webui_all

- name: setup gigaset webui in nginx
  ansible.builtin.template:
    src: gigaset.conf
    dest: "{{ nginx_site_dir }}/gigaset.conf"
    mode: 0644
  become: true
  notify: reload nginx service
  when: ast_webui_server |d('')
  tags: ast_webui_all

- name: apply new nginx settings
  ansible.builtin.meta: flush_handlers
  tags: ast_webui_all
...
