---
## various asterisk defaults


## inherited from role ast_base:
##   ast_reset
##   ast_experimental
##   ast_ssl_cert
##   ast_ssl_key
##   ast_domains
##   ast_default_language
##   ast_default_codecs
##   ast_qualify_value
##   ast_dialplan_hints
##   ast_pg_host
##   ast_pg_port
##   ast_pg_dbname
##   ast_pg_user
##   ast_pg_pass
##   ast_local_dir


ast_softphones: []
# - name: softphone1
#   password: secretpass1
#   exten: 101
#   srtp: false
#   active: true

ast_softphones_secure: true


ast_user_agent: 'Asterisk PBX 13.18'

ast_record_file: /tmp/asterisk-record.wav


ast_pg_dump_url: ""

ast_moh_mp3_tarball_url: https://www.dropbox.com/s/25ue131u8owpir1/moh-extras-mp3.tar.gz?dl=1

ast_sounds_extras_wav_url: https://www.dropbox.com/s/t5i3lxzptnaqetl/sounds-extras-wav.tar.gz?dl=1


## barcelona shows better benchmark performance on a small vps machine
ast_g729_codec_type: ast130-gcc4-glibc2.2-x86_64-barcelona
ast_g729_codec_url: http://asterisk.hosting.lv/bin/codec_g729-{{ ast_g729_codec_type }}.so

ast_g729_bench_enable: false
ast_g729_bench_free_tarball_url: ''
ast_g729_bench_digium_tarball_url: ''


ast_time_sync_enable: true

## do not step-sync time by default to save some playbook time
## if you think syncing is important, set time server to:
## 2.pool.ntp.org
ast_ntp_server: ""


ast_voicemail_pass: 1234

ast_ami_admin_password: ast-ami-secret


## cpu quota examples: 5% 60% 100% false
ast_cpu_quota: false

ast_logrotate_timer: daily  # 'daily' or 'weekly'


## parameters
ast_params_default:
  - file: asterisk
    section: options
    params:
      - execincludes: 'no'
      - systemname: "{{ ast_domains |first }}"
      - runuser: asterisk
      ## Note:
      ## when `rungroup` is set, the asterisk process will have only
      ## those access permissions that are associated with that group.
      ## when `rungroup` is *not* set, but `runuser` is set, the asterisk
      ## process will have access permissions associated with *all*
      ## groups where the user participates.
      ## this allows to control permissions of the asterisk process
      ## more flexibly (e.g. access to ssl certificates).
      # - rungroup: asterisk

ast_params_group: []
ast_params_host: []
...
