---
- name: network whitelist for asterisk providers
  ansible.builtin.include_role:
    name: ivansible.asterisk.core
    tasks_from: _acl.yml
  vars:
    acl: "{{ provider.name }}"
    networks: "{{ provider.networks }}"
    comment: "{{ provider.networks_comment |d(provider.name) }}"
  when:
    - provider.networks is defined
    - provider.networks | length > 0
  loop: "{{ ast_providers | json_query('[?!!active]') }}"
  loop_control:
    loop_var: provider


- name: sip peers for asterisk providers
  ansible.builtin.template:
    src: providers-peers.conf
    dest: /etc/asterisk/sip.d/providers.peers.conf
    owner: root
    group: asterisk
    mode: 0640
  notify: reload asterisk service

- name: dialplan rules for asterisk providers
  ansible.builtin.template:
    src: providers-dialplan.conf
    dest: /etc/asterisk/dialplan.d/providers.rules.conf
    owner: root
    group: asterisk
    mode: 0640
  notify: reload asterisk service


- name: enable other contexts for inward calls from providers
  ansible.builtin.lineinfile:
    path: /etc/asterisk/context.d/providers.conf
    line: "include => {{ item }}"
    create: true
    owner: root
    group: asterisk
    mode: 0640
  loop:
    - softphones
    - "{{ ast_soho_phones_alias }}"
    - services  # optional
  notify: reload asterisk service

- name: enable outward providers calls for other contexts
  ansible.builtin.lineinfile:
    path: /etc/asterisk/context.d/{{ item }}.conf
    line: "include => providers-out"
    create: true
    owner: root
    group: asterisk
    mode: 0640
  loop:
    - softphones
    - "{{ ast_soho_phones_alias }}"
  notify: reload asterisk service
...
